const HANDCRAFTED_DATABASE = {
  sulfuric_acid: {
    name: "Sulfuric Acid",
    formula: "H₂SO₄",
    category: "Acids",
    toxicity: 95,
    hazardCategory: "Highly Corrosive & Reactive",
    waterPollution: "Drastic pH crash, high acidity, toxic sulfate mobilization, severe ecosystem damage.",
    airPollution: "Acidic aerosol emissions, sulfur oxide fumes under thermal load.",
    humanHealthRisk: "Severe deep tissue chemical burns, high hazard of permanent blindness, vapor inhalation leads to fatal pulmonary edema.",
    environmentalRisk: "Severe soil acidification, lethal to aquatic life, dissolves key soil minerals.",
    corrosive: 10,
    flammability: 0,
    nfpa: { health: 3, flammability: 0, instability: 2, special: "W" },
    ppe: [
      "Chemical Splash Hood & Goggles",
      "Heavy Neoprene Gloves (Long Cuff)",
      "Full Acid Hazmat Suit",
      "SBR Rubber Safety Boots",
      "Positive Pressure Vapor Respirator",
    ],
    safeHandling:
      "Always slowly mix acid into water, never reverse. Use acid-proof storage tanks. Keep neutralization agents (sodium carbonate) immediately accessible.",
    detox: {
      neutralization: {
        method: "Exothermic chemical reaction.",
        reaction: "H₂SO₄ + Na₂CO₃ → Na₂SO₄ + H₂O + CO₂",
        monitoring: "pH sensors.",
        recomm: "Sodium Carbonate (Soda Ash)",
        efficiency: 94,
      },
      absorption: {
        method: "Gas scrubbing.",
        technique: "Activated carbon vapor scrubbers.",
        efficiency: 98,
      },
      oxidation: {
        method: "Catalytic precipitation.",
        agents: "Alum dosing.",
        monitoring: "TDS online sensor.",
        efficiency: 72,
      },
      discharge: {
        compliance: "Sulfate levels < 250 mg/L, pH 6.0 - 9.0.",
        quality: "Clean dewatered effluent.",
        recomm: "Lime settling basin.",
        efficiency: 100,
      },
    },
    recommendations: {
      detoxProcess: "Controlled Alkaline Neutralization & Calcium Precipitation",
      filtration: "Microfiltration for calcium sulfate sediment",
      purification: "High-pressure Reverse Osmosis",
      wasteMgmt: "Controlled dewatering of Gypsum slurry",
      safetyStatus: "Danger",
    },
  },
  hydrochloric_acid: {
    name: "Hydrochloric Acid",
    formula: "HCl",
    category: "Acids",
    toxicity: 88,
    hazardCategory: "Corrosive & Volatile Vapor",
    waterPollution: "Rapidly lowers pH, lethal to freshwater species, mobilizes heavy metal ions from mud.",
    airPollution: "Highly toxic hydrogen chloride gas cloud generation, corrosive fog.",
    humanHealthRisk: "Severe eyes/skin burns, mucous membrane damage, throat corrosion on inhalation.",
    environmentalRisk: "Drastic ecosystem acidity changes, soil mineral degradation.",
    corrosive: 9,
    flammability: 0,
    nfpa: { health: 3, flammability: 0, instability: 1, special: "" },
    ppe: [
      "Chemical splash goggles",
      "Full face shield",
      "Nitrile safety gloves",
      "Acid-resistant apron",
    ],
    safeHandling:
      "Avoid inhaling vapors. Use inside gas fume hoods. Store separate from strong bases and oxidizing agents.",
    detox: {
      neutralization: {
        method: "Controlled acid-base balancing.",
        reaction: "HCl + NaOH → NaCl + H₂O",
        monitoring: "pH salt salinity.",
        recomm: "Sodium Carbonate",
        efficiency: 96,
      },
      absorption: {
        method: "Wet scrubber system.",
        technique: "Counter-current gas scrubbers with NaOH spray.",
        efficiency: 99,
      },
      oxidation: {
        method: "Non-oxidizable inorganic.",
        agents: "None.",
        monitoring: "Electrolytic conductivity.",
        efficiency: 40,
      },
      discharge: {
        compliance: "Chloride ions < 200 mg/L, pH 6.5 - 8.5.",
        quality: "Standard saline solution.",
        recomm: "Release post-dilution.",
        efficiency: 100,
      },
    },
    recommendations: {
      detoxProcess: "Fume Scrubbing and Sodium Carbonate Neutralization",
      filtration: "Particulate filtration",
      purification: "Electrodialysis salt control",
      wasteMgmt: "Discharge of neutralized saline wastewater",
      safetyStatus: "Danger",
    },
  },
  nitric_acid: {
    name: "Nitric Acid",
    formula: "HNO₃",
    category: "Acids",
    toxicity: 92,
    hazardCategory: "Strong Oxidizer & Corrosive",
    waterPollution: "Severe acidification and high nutrient nitrate runoff, causing massive algae blooms.",
    airPollution: "Highly toxic yellow/orange nitrogen dioxide (NO₂) gas emissions.",
    humanHealthRisk: "Severe skin burns with characteristic yellow staining, pulmonary edema, eye corrosion.",
    environmentalRisk: "Ecotoxicity to aquatic life, soil acidification, accelerates organic decay dangerously.",
    corrosive: 10,
    flammability: 0,
    nfpa: { health: 4, flammability: 0, instability: 3, special: "OX" },
    ppe: [
      "Acid-proof full face respirator",
      "Heavy rubber boots",
      "Viton gloves",
      "Impervious chemical suit",
    ],
    safeHandling:
      "Keep away from organic fuels, wood, paper. Store in glass container. Highly reactive with metal filings.",
    detox: {
      neutralization: {
        method: "Neutralization.",
        reaction: "2HNO₃ + CaCO₃ → Ca(NO₃)₂ + CO₂ + H₂O",
        monitoring: "pH check.",
        recomm: "Calcium Carbonate",
        efficiency: 93,
      },
      absorption: {
        method: "Gas scrubbing.",
        technique: "Urea wash wet scrubbers.",
        efficiency: 95,
      },
      oxidation: {
        method: "Denitrification bio-reduction.",
        agents: "Denitrifying bio-reactors.",
        monitoring: "Nitrate select electrodes.",
        efficiency: 85,
      },
      discharge: {
        compliance: "Nitrogen < 15 mg/L, pH 6.5 - 9.0.",
        quality: "Clean dewatered effluent.",
        recomm: "Post-neutralization denitrifying bio-reactors.",
        efficiency: 100,
      },
    },
    recommendations: {
      detoxProcess: "Controlled Neutralization & Secondary Biological Denitrification",
      filtration: "Sand bed filtration",
      purification: "Anion exchange column",
      wasteMgmt: "Repurpose calcium nitrate as eco-fertilizer",
      safetyStatus: "Danger",
    },
  },
  acetic_acid: {
    name: "Acetic Acid",
    formula: "CH₃COOH",
    category: "Acids",
    toxicity: 45,
    hazardCategory: "Organic Acid & Combustible",
    waterPollution: "High BOD (Biological Oxygen Demand) causing localized oxygen depletion.",
    airPollution: "Pungent sour fumes, volatile organic carbon (VOC).",
    humanHealthRisk: "Eye irritation, skin burns at high concentrations, throat irritation on inhalation.",
    environmentalRisk: "Moderate aquatic toxicity, fully biodegradable under aerobic conditions.",
    corrosive: 5,
    flammability: 2,
    nfpa: { health: 3, flammability: 2, instability: 0, special: "" },
    ppe: [
      "Chemical goggles",
      "Neoprene safety gloves",
      "Fume hood ventilation",
      "Lab coat",
    ],
    safeHandling:
      "Keep away from open heat sources. Store separate from strong oxidizers like nitric acid.",
    detox: {
      neutralization: {
        method: "Mild alkali neutralizing.",
        reaction: "CH₃COOH + NaNaHCO₃ → CH₃COONa + H₂O + CO₂",
        monitoring: "pH stabilization.",
        recomm: "Sodium Bicarbonate",
        efficiency: 95,
      },
      absorption: {
        method: "Carbon absorption.",
        technique: "Granular activated carbon filters.",
        efficiency: 90,
      },
      oxidation: {
        method: "Biological biodegradation.",
        agents: "Activated sludge bacteria.",
        monitoring: "BOD and COD real-time check.",
        efficiency: 94,
      },
      discharge: {
        compliance: "BOD < 30 mg/L, pH 6.0 - 9.0.",
        quality: "Safe organic water.",
        recomm: "Secondary activated sludge release.",
        efficiency: 100,
      },
    },
    recommendations: {
      detoxProcess: "Mild Alkaline Buffering & Standard Aerobic Biotreatment",
      filtration: "Activated Carbon Filtration",
      purification: "Bio-membrane purification",
      wasteMgmt: "Safe discharge directly to municipal sewage",
      safetyStatus: "Alert",
    },
  },
  sodium_hydroxide: {
    name: "Sodium Hydroxide (Caustic Soda)",
    formula: "NaOH",
    category: "Bases",
    toxicity: 90,
    hazardCategory: "Highly Corrosive Strong Base",
    waterPollution: "Spike in pH levels (>12) instantly lethal to all aquatic organisms.",
    airPollution: "Low volatile vapor, but highly dangerous alkaline aerosols.",
    humanHealthRisk: "Deep saponification tissue burns, liquefies protein tissue, permanent blindness hazard.",
    environmentalRisk: "Severe damage to vegetation and soil structure, sterilizes water bodies.",
    corrosive: 10,
    flammability: 0,
    nfpa: { health: 3, flammability: 0, instability: 1, special: "" },
    ppe: [
      "Chemical splash goggles",
      "Full face shield",
      "Heavy neoprene gloves",
      "Alkali-resistant apron",
      "Safety boots",
    ],
    safeHandling:
      "Highly exothermic reaction when dissolving. Store separate from strong acids and chlorinated solvents.",
    detox: {
      neutralization: {
        method: "Exothermic base neutralization.",
        reaction: "NaOH + HCl → NaCl + H₂O",
        monitoring: "Real-time pH down-titration.",
        recomm: "Dilute Hydrochloric Acid",
        efficiency: 97,
      },
      absorption: {
        method: "Containment of liquid wash.",
        technique: "Dike containment and batch reactors.",
        efficiency: 99,
      },
      oxidation: {
        method: "Inorganic compound, not oxidizable.",
        agents: "None.",
        monitoring: "None.",
        efficiency: 20,
      },
      discharge: {
        compliance: "Sodium < 200 mg/L, pH 6.0 - 9.0.",
        quality: "Neutral salt brine.",
        recomm: "Slow municipal release.",
        efficiency: 100,
      },
    },
    recommendations: {
      detoxProcess: "Dilute Acid Neutralization & Salinity Dilution",
      filtration: "Standard mechanical pre-filter",
      purification: "Reverse Osmosis salt concentration",
      wasteMgmt: "Discharge of neutralized brine",
      safetyStatus: "Danger",
    },
  },
  ammonia: {
    name: "Ammonia (Aqueous)",
    formula: "NH₃ (aq)",
    category: "Bases",
    toxicity: 80,
    hazardCategory: "Toxic Gas Precursor & Corrosive Base",
    waterPollution: "Highly toxic ammonium ions, triggers mass fish kills, depletes biological oxygen.",
    airPollution: "Releases suffocating, toxic ammonia gas, noxious fumes.",
    humanHealthRisk: "Severe respiratory track corrosion, blindness hazard, skin burns.",
    environmentalRisk: "Ecotoxicity to aquatic life, soil toxicity at high concentrations.",
    corrosive: 8,
    flammability: 1,
    nfpa: { health: 3, flammability: 1, instability: 0, special: "" },
    ppe: [
      "Full chemical respirator with green NH3 cartridge",
      "Nitrile long gloves",
      "Splash goggles",
    ],
    safeHandling:
      "Store in tightly sealed, refrigerated containers. Always handle in high-airflow environments.",
    detox: {
      neutralization: {
        method: "Neutralization to ammonium salt.",
        reaction: "NH₃ + HNO₃ → NH₄NO₃",
        monitoring: "pH and free ammonia levels.",
        recomm: "Dilute Sulfuric Acid",
        efficiency: 95,
      },
      absorption: {
        method: "Ammonia scrubbing tower.",
        technique: "Acid wash pack bed scrubbers.",
        efficiency: 98,
      },
      oxidation: {
        method: "Biological nitrification.",
        agents: "Nitrifying bacteria bio-filter.",
        monitoring: "Total Nitrogen.",
        efficiency: 91,
      },
      discharge: {
        compliance: "Free ammonia < 1.0 mg/L.",
        quality: "Post-nitrified safe effluent.",
        recomm: "Biological nitrification-denitrification polish.",
        efficiency: 100,
      },
    },
    recommendations: {
      detoxProcess: "Acid Wet Scrubbing & Biological Nitrification",
      filtration: "Membrane bioreactor",
      purification: "Zeolite adsorption column",
      wasteMgmt: "Evaporation crystallizer for fertilizer salt",
      safetyStatus: "Danger",
    },
  },
  hydrogen_peroxide: {
    name: "Hydrogen Peroxide (Industrial)",
    formula: "H₂O₂",
    category: "Bleaching Chemicals",
    toxicity: 70,
    hazardCategory: "Strong Oxidizer & Corrosive",
    waterPollution: "Sterilizes aquatic bacterial chains instantly, oxidizes organic matter rapidly.",
    airPollution: "Pungent oxygenating fumes, corrosive vapor at high concentrations.",
    humanHealthRisk: "Corrosive skin bleaching/burns, severe eye destruction, inhalation throat blister hazard.",
    environmentalRisk: "High ecotoxicity, depletes ecological baseline microbes.",
    corrosive: 8,
    flammability: 0,
    nfpa: { health: 3, flammability: 0, instability: 2, special: "OX" },
    ppe: [
      "Splash goggles",
      "Butyl safety gloves",
      "Breathing mask",
      "Vinyl apron",
    ],
    safeHandling:
      "Violent decomposition hazard if mixed with metal dust or catalysts. Store in vented, dark containers.",
    detox: {
      neutralization: {
        method: "Catalytic decomposition.",
        reaction: "2H₂O₂ → 2H₂O + O₂",
        monitoring: "Oxygen release rates.",
        recomm: "Activated Carbon or Bisulfite",
        efficiency: 98,
      },
      absorption: {
        method: "Gaseous condensation.",
        technique: "Chilled condensation towers.",
        efficiency: 90,
      },
      oxidation: {
        method: "Acts as strong oxidizer.",
        agents: "None.",
        monitoring: "Residual levels.",
        efficiency: 99,
      },
      discharge: {
        compliance: "H₂O₂ < 1.0 mg/L.",
        quality: "Pure water and DO.",
        recomm: "Verify decomposition with test strips.",
        efficiency: 100,
      },
    },
    recommendations: {
      detoxProcess: "Sodium Bisulfite Chemical Reduction or Activated Carbon Catalytic Breakdown",
      filtration: "Standard mechanical",
      purification: "Manganese oxide filtration beds",
      wasteMgmt: "Safe sewage discharge of water byproduct",
      safetyStatus: "Danger",
    },
  },
  sodium_hypochlorite: {
    name: "Sodium Hypochlorite (Industrial Bleach)",
    formula: "NaOCl",
    category: "Bleaching Chemicals",
    toxicity: 75,
    hazardCategory: "Corrosive & Reactive Chlorine Source",
    waterPollution: "Forms toxic persistent organochlorines (AOX), extremely toxic to aquatic organisms.",
    airPollution: "Releases corrosive, toxic chlorine gas if mixed with acids.",
    humanHealthRisk: "Caustic burns, throat irritation, severe eye destruction.",
    environmentalRisk: "Creates carcinogenic chlorinated compounds in freshwater ecosystems.",
    corrosive: 8,
    flammability: 0,
    nfpa: { health: 3, flammability: 0, instability: 1, special: "" },
    ppe: [
      "Chlorine gas mask option",
      "Nitrile gloves",
      "Eye shield glasses",
    ],
    safeHandling:
      "NEVER mix with acids or ammonia (produces lethal chlorine/chloramine gases). Store in cool, dark ventilated locations.",
    detox: {
      neutralization: {
        method: "Chemical reduction to safe salt.",
        reaction: "NaOCl + NaHSO₃ → NaCl + NaHSO₄",
        monitoring: "ORP sensors.",
        recomm: "Sodium Bisulfite",
        efficiency: 98,
      },
      absorption: {
        method: "Gas scrubbers.",
        technique: "Alkaline packed column.",
        efficiency: 97,
      },
      oxidation: {
        method: "Acts as strong oxidizer.",
        agents: "None.",
        monitoring: "ORP.",
        efficiency: 96,
      },
      discharge: {
        compliance: "Free chlorine < 0.2 mg/L.",
        quality: "Slightly saline salt water.",
        recomm: "Batch dechlorination check.",
        efficiency: 100,
      },
    },
    recommendations: {
      detoxProcess: "Sodium Bisulfite Chemical Reduction & Declorination",
      filtration: "Activated carbon filter (strips trace chlorine)",
      purification: "None required",
      wasteMgmt: "Direct municipal release of dechlorinated salt stream",
      safetyStatus: "Danger",
    },
  },
  hydrogen_sulfide: {
    name: "Hydrogen Sulfide",
    formula: "H₂S",
    category: "Harmful Gases",
    toxicity: 96,
    hazardCategory: "Lethal Flammable Gas & Olfactory Paralyzer",
    waterPollution: "Causes intense fish kills, creates rotten egg odors, oxygen depletion.",
    airPollution: "Highly toxic and highly flammable gas, rapid olfactory fatigue.",
    humanHealthRisk: "Rapidly blocks cellular respiration, causes instant death at >700 ppm.",
    environmentalRisk: "Ecotoxicity to mammals and fish, highly persistent in air.",
    corrosive: 6,
    flammability: 10,
    nfpa: { health: 4, flammability: 4, instability: 0, special: "" },
    ppe: [
      "SCBA respirator system",
      "Explosion proof gas safety clothing",
      "Personal H2S sound alarm detector",
    ],
    safeHandling:
      "Ground cylinders. Eliminate all static. Work under strict multi-detector alarms. Avoid entering deep pits without ventilation.",
    detox: {
      neutralization: {
        method: "Catalytic oxidation.",
        reaction: "2H₂S + O₂ → 2S↓ + 2H₂O (Claus)",
        monitoring: "H₂S stack gas alarms.",
        recomm: "Catalytic Iron Chelate",
        efficiency: 97,
      },
      absorption: {
        method: "Iron sponge adsorption.",
        technique: "Granular iron oxide filter beds.",
        efficiency: 99,
      },
      oxidation: {
        method: "Bleach chemical scrubbing.",
        agents: "H₂O₂ or Sodium Hypochlorite.",
        monitoring: "Redox levels.",
        efficiency: 95,
      },
      discharge: {
        compliance: "Air emission < 1.0 ppm, liquid sulfide < 0.1 mg/L.",
        quality: "Elemental sulfur sludge byproduct.",
        recomm: "Isolate precipitated sulfur solids.",
        efficiency: 100,
      },
    },
    recommendations: {
      detoxProcess: "Iron Oxide Sponge Adsorption & Bleach Oxidation Scrubbing",
      filtration: "Dry iron sponge cartridge system",
      purification: "Activated bio-filter beds",
      wasteMgmt: "Recycle elemental sulfur byproduct",
      safetyStatus: "Danger",
    },
  },
  formaldehyde: {
    name: "Formaldehyde",
    formula: "HCHO",
    category: "Dyeing Industry Auxiliaries",
    toxicity: 88,
    hazardCategory: "Carcinogen & Highly Reactive VOC",
    waterPollution: "Toxic to aquatic life, high biological oxygen depletion.",
    airPollution: "High carcinogenic volatility, strong tear-gas vapor.",
    humanHealthRisk: "Proven human carcinogen (causes nasal cancers), severe skin sensitizer, tearing eyes.",
    environmentalRisk: "Mutagenic to water organisms, breaks down slowly in dark waters.",
    corrosive: 5,
    flammability: 4,
    nfpa: { health: 3, flammability: 2, instability: 2, special: "" },
    ppe: [
      "Vapor respirator with formaldehyde cartridge",
      "Viton gloves",
      "Safety goggles",
      "Air extraction hood",
    ],
    safeHandling:
      "Limit exposure time. Store in warm container to prevent paraformaldehyde crystallization. Use closed process loops.",
    detox: {
      neutralization: {
        method: "Chemical conversion.",
        reaction: "6HCHO + 4NH₃ → Hexamine",
        monitoring: "Formaldehyde sensor arrays.",
        recomm: "Ammonia Dosing",
        efficiency: 94,
      },
      absorption: {
        method: "Carbon extraction.",
        technique: "GAC filter beds.",
        efficiency: 94,
      },
      oxidation: {
        method: "Advanced Oxidation Process (Fenton's).",
        agents: "Fenton's reagent.",
        monitoring: "TOC monitoring.",
        efficiency: 97,
      },
      discharge: {
        compliance: "Formaldehyde levels < 0.1 mg/L.",
        quality: "Safe clean water.",
        recomm: "Final analytical HPLC verify.",
        efficiency: 100,
      },
    },
    recommendations: {
      detoxProcess: "Fenton's Advanced Oxidation & Granular Carbon Treatment",
      filtration: "Activated carbon polishing filter",
      purification: "Anion exchange column",
      wasteMgmt: "Incinerate contaminated carbon filters",
      safetyStatus: "Danger",
    },
  },
};

const ADDITIONAL_DATABASE_TEMPLATES = [
  { key: "hydrofluoric_acid", name: "Hydrofluoric Acid", formula: "HF", category: "Acids", toxicity: 98, corrosive: 10, flammability: 0, nfpa: { health: 4, flammability: 0, instability: 1, special: "" } },
  { key: "boric_acid", name: "Boric Acid", formula: "H₃BO₃", category: "Acids", toxicity: 25, corrosive: 1, flammability: 0, nfpa: { health: 1, flammability: 0, instability: 0, special: "" } },
  { key: "chromic_acid", name: "Chromic Acid", formula: "H₂CrO₄", category: "Acids", toxicity: 96, corrosive: 9, flammability: 0, nfpa: { health: 4, flammability: 0, instability: 1, special: "OX" } },
  { key: "carbonic_acid", name: "Carbonic Acid", formula: "H₂CO₃", category: "Acids", toxicity: 10, corrosive: 1, flammability: 0, nfpa: { health: 0, flammability: 0, instability: 0, special: "" } },
  { key: "perchloric_acid", name: "Perchloric Acid", formula: "HClO₄", category: "Acids", toxicity: 94, corrosive: 10, flammability: 0, nfpa: { health: 3, flammability: 0, instability: 3, special: "OX" } },
  { key: "malic_acid", name: "Malic Acid", formula: "C₄H₆O₅", category: "Acids", toxicity: 22, corrosive: 2, flammability: 1, nfpa: { health: 1, flammability: 1, instability: 0, special: "" } },
  { key: "succinic_acid", name: "Succinic Acid", formula: "C₄H₆O₄", category: "Acids", toxicity: 24, corrosive: 2, flammability: 1, nfpa: { health: 1, flammability: 1, instability: 0, special: "" } },
  { key: "benzoic_acid", name: "Benzoic Acid", formula: "C₇H₆O₂", category: "Acids", toxicity: 30, corrosive: 3, flammability: 1, nfpa: { health: 2, flammability: 1, instability: 0, special: "" } },
  { key: "salicylic_acid", name: "Salicylic Acid", formula: "C₇H₆O₃", category: "Acids", toxicity: 35, corrosive: 3, flammability: 1, nfpa: { health: 2, flammability: 1, instability: 0, special: "" } },
  { key: "phthalic_acid", name: "Phthalic Acid", formula: "C₈H₆O₄", category: "Acids", toxicity: 38, corrosive: 3, flammability: 1, nfpa: { health: 2, fontStyle: 1, instability: 0, special: "" } },
  { key: "lithium_hydroxide", name: "Lithium Hydroxide", formula: "LiOH", category: "Bases", toxicity: 85, corrosive: 9, flammability: 0, nfpa: { health: 3, flammability: 0, instability: 1, special: "" } },
  { key: "barium_hydroxide", name: "Barium Hydroxide", formula: "Ba(OH)₂", category: "Bases", toxicity: 82, corrosive: 8, flammability: 0, nfpa: { health: 3, flammability: 0, instability: 1, special: "" } },
  { key: "caesium_hydroxide", name: "Caesium Hydroxide", formula: "CsOH", category: "Bases", toxicity: 88, corrosive: 10, flammability: 0, nfpa: { health: 3, flammability: 0, instability: 1, special: "" } },
  { key: "calcium_oxide", name: "Calcium Oxide (Quicklime)", formula: "CaO", category: "Bases", toxicity: 62, corrosive: 7, flammability: 0, nfpa: { health: 3, flammability: 0, instability: 1, special: "W" } },
  { key: "sodium_metasilicate", name: "Sodium Metasilicate", formula: "Na₂SiO₃", category: "Bases", toxicity: 50, corrosive: 6, flammability: 0, nfpa: { health: 3, flammability: 0, instability: 0, special: "" } },
  { key: "ammonium_hydroxide", name: "Ammonium Hydroxide", formula: "NH₄OH", category: "Bases", toxicity: 78, corrosive: 8, flammability: 1, nfpa: { health: 3, flammability: 1, instability: 0, special: "" } },
  { key: "hydrazine", name: "Hydrazine", formula: "N₂H₄", category: "Bases", toxicity: 94, corrosive: 7, flammability: 4, nfpa: { health: 4, flammability: 4, instability: 2, special: "" } },
  { key: "tetraethylammonium_hydroxide", name: "Tetraethylammonium Hydroxide", formula: "(C₂H₅)₄NOH", category: "Bases", toxicity: 80, corrosive: 8, flammability: 1, nfpa: { health: 3, flammability: 1, instability: 0, special: "" } },
  { key: "sodium_perborate", name: "Sodium Perborate", formula: "NaBO₃", category: "Bleaching Chemicals", toxicity: 48, corrosive: 4, flammability: 0, nfpa: { health: 2, flammability: 0, instability: 1, special: "OX" } },
  { key: "calcium_hypochlorite", name: "Calcium Hypochlorite", formula: "Ca(OCl)₂", category: "Bleaching Chemicals", toxicity: 82, corrosive: 9, flammability: 0, nfpa: { health: 3, flammability: 0, instability: 1, special: "OX" } },
  { key: "ozone_aqueous", name: "Ozone (Aqueous)", formula: "O₃ (aq)", category: "Bleaching Chemicals", toxicity: 65, corrosive: 5, flammability: 0, nfpa: { health: 3, flammability: 0, instability: 2, special: "OX" } },
  { key: "peracetic_acid", name: "Peracetic Acid", formula: "CH₃CO₃H", category: "Bleaching Chemicals", toxicity: 80, corrosive: 9, flammability: 2, nfpa: { health: 3, flammability: 2, instability: 2, special: "OX" } },
  { key: "benzoyl_peroxide", name: "Benzoyl Peroxide", formula: "(C₆H₅CO)₂O₂", category: "Bleaching Chemicals", toxicity: 55, corrosive: 3, flammability: 3, nfpa: { health: 2, flammability: 3, instability: 3, special: "OX" } },
  { key: "sodium_chlorite", name: "Sodium Chlorite", formula: "NaClO₂", category: "Bleaching Chemicals", toxicity: 76, corrosive: 8, flammability: 0, nfpa: { health: 3, flammability: 0, instability: 2, special: "OX" } },
  { key: "chloroform", name: "Chloroform", formula: "CHCl₃", category: "Solvents", toxicity: 85, corrosive: 0, flammability: 0, nfpa: { health: 3, flammability: 0, instability: 0, special: "" } },
  { key: "dichloromethane", name: "Dichloromethane", formula: "CH₂Cl₂", category: "Solvents", toxicity: 70, corrosive: 0, flammability: 1, nfpa: { health: 2, flammability: 1, instability: 0, special: "" } },
  { key: "trichloroethylene", name: "Trichloroethylene (TCE)", formula: "C₂HCl₃", category: "Solvents", toxicity: 82, corrosive: 0, flammability: 1, nfpa: { health: 3, flammability: 1, instability: 0, special: "" } },
  { key: "hexane", name: "Hexane", formula: "C₆H₁₄", category: "Solvents", toxicity: 64, corrosive: 0, flammability: 3, nfpa: { health: 2, flammability: 3, instability: 0, special: "" } },
  { key: "heptane", name: "Heptane", formula: "C₇H₁₆", category: "Solvents", toxicity: 60, corrosive: 0, flammability: 3, nfpa: { health: 2, flammability: 3, instability: 0, special: "" } },
  { key: "diethyl_ether", name: "Diethyl Ether", formula: "(C₂H₅)₂O", category: "Solvents", toxicity: 62, corrosive: 0, flammability: 4, nfpa: { health: 2, flammability: 4, instability: 1, special: "" } },
  { key: "tetrahydrofuran", name: "Tetrahydrofuran (THF)", formula: "C₄H₈O", category: "Solvents", toxicity: 68, corrosive: 0, flammability: 3, nfpa: { health: 2, flammability: 3, instability: 1, special: "" } },
  { key: "dimethyl_sulfoxide", name: "Dimethyl Sulfoxide (DMSO)", formula: "(CH₃)₂SO", category: "Solvents", toxicity: 20, corrosive: 0, flammability: 1, nfpa: { health: 1, flammability: 1, instability: 0, special: "" } },
  { key: "dimethylformamide", name: "Dimethylformamide (DMF)", formula: "HCON(CH₃)₂", category: "Solvents", toxicity: 75, corrosive: 0, flammability: 2, nfpa: { health: 2, flammability: 2, instability: 0, special: "" } },
  { key: "ethyl_acetate", name: "Ethyl Acetate", formula: "CH₃COOCH₂CH₃", category: "Solvents", toxicity: 38, corrosive: 0, flammability: 3, nfpa: { health: 1, flammability: 3, instability: 0, special: "" } },
  { key: "acetonitrile", name: "Acetonitrile", formula: "CH₃CN", category: "Solvents", toxicity: 78, corrosive: 0, flammability: 3, nfpa: { health: 2, flammability: 3, instability: 0, special: "" } },
  { key: "isopropyl_alcohol", name: "Isopropyl Alcohol (IPA)", formula: "C₃H₈O", category: "Solvents", toxicity: 32, corrosive: 0, flammability: 3, nfpa: { health: 1, flammability: 3, instability: 0, special: "" } },
  { key: "carbon_tetrachloride", name: "Carbon Tetrachloride", formula: "CCl₄", category: "Solvents", toxicity: 94, corrosive: 0, flammability: 0, nfpa: { health: 4, flammability: 0, instability: 0, special: "" } },
  { key: "nickel_compounds", name: "Nickel Compounds", formula: "Ni²⁺", category: "Heavy Metals", toxicity: 82, corrosive: 0, flammability: 0, nfpa: { health: 3, flammability: 0, instability: 0, special: "" } },
  { key: "copper_compounds", name: "Copper Compounds", formula: "Cu²⁺", category: "Heavy Metals", toxicity: 68, corrosive: 1, flammability: 0, nfpa: { health: 2, flammability: 0, instability: 0, special: "" } },
  { key: "zinc_compounds", name: "Zinc Compounds", formula: "Zn²⁺", category: "Heavy Metals", toxicity: 45, corrosive: 1, flammability: 0, nfpa: { health: 2, flammability: 0, instability: 0, special: "" } },
  { key: "cobalt_compounds", name: "Cobalt Compounds", formula: "Co²⁺", category: "Heavy Metals", toxicity: 78, corrosive: 0, flammability: 0, nfpa: { health: 3, flammability: 0, instability: 0, special: "" } },
  { key: "barium_compounds", name: "Barium Compounds", formula: "Ba²⁺", category: "Heavy Metals", toxicity: 80, corrosive: 2, flammability: 0, nfpa: { health: 3, flammability: 0, instability: 0, special: "" } },
  { key: "antimony_compounds", name: "Antimony Compounds", formula: "Sb²⁺", category: "Heavy Metals", toxicity: 84, corrosive: 1, flammability: 0, nfpa: { health: 3, flammability: 0, instability: 0, special: "" } },
  { key: "thallium_compounds", name: "Thallium Compounds", formula: "Tl⁺ / Tl³⁺", category: "Heavy Metals", toxicity: 96, corrosive: 0, flammability: 0, nfpa: { health: 4, flammability: 0, instability: 0, special: "" } },
  { key: "beryllium_compounds", name: "Beryllium Compounds", formula: "Be²⁺", category: "Heavy Metals", toxicity: 95, corrosive: 0, flammability: 0, nfpa: { health: 4, flammability: 0, instability: 0, special: "" } },
  { key: "selenium_compounds", name: "Selenium Compounds", formula: "SeO₃²⁻", category: "Heavy Metals", toxicity: 76, corrosive: 1, flammability: 0, nfpa: { health: 3, flammability: 0, instability: 0, special: "" } },
  { key: "carbon_monoxide", name: "Carbon Monoxide", formula: "CO", category: "Harmful Gases", toxicity: 88, corrosive: 0, flammability: 4, nfpa: { health: 4, flammability: 4, instability: 0, special: "" } },
  { key: "nitrogen_dioxide", name: "Nitrogen Dioxide", formula: "NO₂", category: "Harmful Gases", toxicity: 90, corrosive: 8, flammability: 0, nfpa: { health: 4, flammability: 0, instability: 0, special: "OX" } },
  { key: "phosgene", name: "Phosgene", formula: "COCl₂", category: "Harmful Gases", toxicity: 99, corrosive: 6, flammability: 0, nfpa: { health: 4, flammability: 0, instability: 0, special: "" } },
  { key: "cyanogen_chloride", name: "Cyanogen Chloride", formula: "CNCl", category: "Harmful Gases", toxicity: 98, corrosive: 5, flammability: 0, nfpa: { health: 4, flammability: 0, instability: 1, special: "" } },
  { key: "hydrogen_cyanide", name: "Hydrogen Cyanide", formula: "HCN", category: "Harmful Gases", toxicity: 99, corrosive: 0, flammability: 4, nfpa: { health: 4, flammability: 4, instability: 2, special: "" } },
  { key: "sulfur_hexafluoride", name: "Sulfur Hexafluoride", formula: "SF₆", category: "Harmful Gases", toxicity: 20, corrosive: 0, flammability: 0, nfpa: { health: 1, flammability: 0, instability: 0, special: "" } },
  { key: "methyl_isocyanate", name: "Methyl Isocyanate", formula: "CH₃NCO", category: "Harmful Gases", toxicity: 99, corrosive: 3, flammability: 3, nfpa: { health: 4, flammability: 3, instability: 2, special: "W" } },
  { key: "arsine", name: "Arsine Gas", formula: "AsH₃", category: "Harmful Gases", toxicity: 98, corrosive: 0, flammability: 4, nfpa: { health: 4, flammability: 4, instability: 2, special: "" } },
  { key: "phosphine", name: "Phosphine Gas", formula: "PH₃", category: "Harmful Gases", toxicity: 97, corrosive: 0, flammability: 4, nfpa: { health: 4, flammability: 4, instability: 2, special: "" } },
  { key: "alum", name: "Alum (Potassium Alum)", formula: "KAl(SO₄)₂", category: "Dyeing Industry Auxiliaries", toxicity: 30, corrosive: 3, flammability: 0, nfpa: { health: 1, flammability: 0, instability: 0, special: "" } },
  { key: "polyethylene_glycol", name: "Polyethylene Glycol", formula: "PEG", category: "Dyeing Industry Auxiliaries", toxicity: 15, corrosive: 0, flammability: 1, nfpa: { health: 0, flammability: 1, instability: 0, special: "" } },
  { key: "acetic_anhydride", name: "Acetic Anhydride", formula: "(CH₃CO)₂O", category: "Dyeing Industry Auxiliaries", toxicity: 82, corrosive: 8, flammability: 2, nfpa: { health: 3, flammability: 2, instability: 1, special: "W" } },
  { key: "sodium_dithionite", name: "Sodium Dithionite", formula: "Na₂S₂O₄", category: "Dyeing Industry Auxiliaries", toxicity: 62, corrosive: 3, flammability: 2, nfpa: { health: 2, flammability: 2, instability: 2, special: "" } },
  { key: "sodium_sulfate", name: "Sodium Sulfate", formula: "Na₂SO₄", category: "Dyeing Industry Auxiliaries", toxicity: 12, corrosive: 0, flammability: 0, nfpa: { health: 1, flammability: 0, instability: 0, special: "" } },
  { key: "sodium_chloride", name: "Sodium Chloride (Saline)", formula: "NaCl", category: "Dyeing Industry Auxiliaries", toxicity: 10, corrosive: 0, flammability: 0, nfpa: { health: 0, flammability: 0, instability: 0, special: "" } },
  { key: "reactive_black_5", name: "Reactive Black 5", formula: "Organic Azo Dye", category: "Dyeing Industry Auxiliaries", toxicity: 50, corrosive: 1, flammability: 1, nfpa: { health: 2, flammability: 1, instability: 0, special: "" } },
  { key: "disperse_blue_79", name: "Disperse Blue 79", formula: "Anthraquinone Dye", category: "Dyeing Industry Auxiliaries", toxicity: 52, corrosive: 0, flammability: 1, nfpa: { health: 2, flammability: 1, instability: 0, special: "" } },
  { key: "acid_red_1", name: "Acid Red 1 (Azophloxine)", formula: "Azo Dye Salt", category: "Dyeing Industry Auxiliaries", toxicity: 48, corrosive: 1, flammability: 1, nfpa: { health: 2, flammability: 1, instability: 0, special: "" } },
  { key: "direct_yellow_12", name: "Direct Yellow 12 (Chrysophenine)", formula: "Stilbene Dye", category: "Dyeing Industry Auxiliaries", toxicity: 46, corrosive: 0, flammability: 1, nfpa: { health: 1, flammability: 1, instability: 0, special: "" } },
  { key: "vat_green_1", name: "Vat Green 1 (Jade Green)", formula: "Violanthrone Dye", category: "Dyeing Industry Auxiliaries", toxicity: 42, corrosive: 0, flammability: 1, nfpa: { health: 1, flammability: 1, instability: 0, special: "" } },
  { key: "indigo_pure", name: "Indigo Pure", formula: "C₁₆H₁₀N₂O₂", category: "Dyeing Industry Auxiliaries", toxicity: 35, corrosive: 0, flammability: 1, nfpa: { health: 1, flammability: 1, instability: 0, special: "" } },
  { key: "sulphur_black_1", name: "Sulphur Black 1", formula: "Polymeric Dye", category: "Dyeing Industry Auxiliaries", toxicity: 58, corrosive: 2, flammability: 1, nfpa: { health: 2, flammability: 1, instability: 0, special: "" } },
  { key: "mordant_brown_33", name: "Mordant Brown 33", formula: "Chrome Dye Complex", category: "Dyeing Industry Auxiliaries", toxicity: 72, corrosive: 1, flammability: 1, nfpa: { health: 3, flammability: 1, instability: 0, special: "" } },
  { key: "sodium_silicate", name: "Sodium Silicate (Waterglass)", formula: "Na₂SiO₃", category: "Dyeing Industry Auxiliaries", toxicity: 40, corrosive: 5, flammability: 0, nfpa: { health: 2, flammability: 0, instability: 0, special: "" } },
  { key: "edta", name: "EDTA Chelating Agent", formula: "C₁₀H₁₆N₂O₈", category: "Dyeing Industry Auxiliaries", toxicity: 35, corrosive: 1, flammability: 1, nfpa: { health: 2, flammability: 1, instability: 0, special: "" } },
  { key: "aerosol_ot", name: "Aerosol OT (Wetting Agent)", formula: "Dioctyl Sulfosuccinate", category: "Dyeing Industry Auxiliaries", toxicity: 38, corrosive: 2, flammability: 1, nfpa: { health: 2, flammability: 1, instability: 0, special: "" } },
  { key: "trichlorobenzene", name: "Trichlorobenzene", formula: "C₆H₃Cl₃", category: "Dyeing Industry Auxiliaries", toxicity: 78, corrosive: 1, flammability: 1, nfpa: { health: 3, flammability: 1, instability: 0, special: "" } },
  { key: "urea", name: "Urea", formula: "CO(NH₂)₂", category: "Dyeing Industry Auxiliaries", toxicity: 15, corrosive: 0, flammability: 1, nfpa: { health: 1, flammability: 1, instability: 0, special: "" } },
  { key: "polyacrylamide", name: "Polyacrylamide (PAM)", formula: "(C₃H₅NO)n", category: "Dyeing Industry Auxiliaries", toxicity: 25, corrosive: 0, flammability: 0, nfpa: { health: 1, flammability: 0, instability: 0, special: "" } }
];

export const buildDefaultChemicalDatabase = () => {
  const db = { ...HANDCRAFTED_DATABASE };

  ADDITIONAL_DATABASE_TEMPLATES.forEach((item) => {
    const isDanger = item.toxicity >= 80;
    const isAlert = item.toxicity >= 40 && item.toxicity < 80;
    const safetyStatus = isDanger ? "Danger" : isAlert ? "Alert" : "Safe";

    const maxTreatmentEfficiency = isDanger ? 94 + (item.toxicity % 5) : 99.2;

    db[item.key] = {
      name: item.name,
      formula: item.formula,
      category: item.category,
      toxicity: item.toxicity,
      corrosive: item.corrosive,
      flammability: item.flammability,
      nfpa: item.nfpa,
      hazardCategory: `${item.category} Threat Compound`,
      waterPollution: `Modifies aquatic pH/salinity, presents significant biological oxygen demand. Highly persistent under low dilution streams.`,
      airPollution: `${item.category} vapor and particulate dispersion hazard. Dangerous to inhale under thermal agitation.`,
      humanHealthRisk: `Causes localized eye and skin chemical burns. Vapor inhalation damages deep respiratory pathways.`,
      environmentalRisk: `Low bioaccumulation, but causes acute ecotoxicity to freshwater micro-fauna and riparian systems.`,
      ppe: [
        "Safety Glasses with Side Shields",
        "Nitrile Chemical Safety Work Gloves",
        "Industrial protective lab apron",
        "Fume extraction hood ventilation",
      ],
      safeHandling: `Store in cool, dry, well-ventilated chemical safety cabinets. Seal caps tightly to prevent hydration. Keep away from active ignition sources.`,
      detox: {
        neutralization: {
          method: "Standard buffering or stoichiometric adjustment.",
          reaction:
            item.category === "Acids"
              ? "Acid + Na₂CO₃ → Salt + H₂O + CO₂"
              : item.category === "Bases"
              ? "Base + CH₃COOH → Salt + H₂O"
              : "Physical buffering active",
          monitoring: "pH sensors.",
          recomm:
            item.category === "Acids"
              ? "Sodium Carbonate"
              : item.category === "Bases"
              ? "Acetic Acid"
              : "Sodium Bicarbonate buffer",
          efficiency: 92,
        },
        absorption: {
          method: "Granular active carbon adsorption.",
          technique: "Static filters.",
          efficiency: 95,
        },
        oxidation: {
          method: "UV-enhanced oxidation.",
          agents: "Hydrogen Peroxide (H₂O₂).",
          monitoring: "COD/TOC online meters.",
          efficiency: 90,
        },
        discharge: {
          compliance: "Compliance cleared. TDS < 1000 mg/L, pH 6.5 - 8.5.",
          quality: "Safe effluent water.",
          recomm: "Final sand filter bed polishing.",
          efficiency: maxTreatmentEfficiency,
        },
      },
      recommendations: {
        detoxProcess: `Controlled Batch ${
          item.category === "Acids"
            ? "Neutralization"
            : item.category === "Bases"
            ? "Buffering"
            : "Oxidation"
        } & Adsorption`,
        filtration: "Dual-Media Sand & Carbon Filtration",
        purification: "Standard membrane filtration Polish",
        wasteMgmt: "Standard municipal industrial wastewater discharge",
        safetyStatus: safetyStatus,
      },
    };
  });
  return db;
};
